@swagger
/applicant/edit/{userId}:
   put:
     summary: Get one applicant with ID
     tags:  [Application]
     description: Retrieve a list of all applicants users
     parameters:
       - name: userId
         in: path
         description: Numerical ID required
         required: true
         schema:
           type: integer
       - name: userupdate
         in: body
          description: Fill all is required
          required: true
             name:
               type: string
             email:
               type: string
               format: email
             phone:
               type: string
               format: password
             position:
               type: string
             link:
               type: string
           
     responses:
       200:
         description: A list of applicants
       500:
         description: Internal server error
 